[package]
name = "executor"
version = "0.1.0"
edition = "2024"

[dependencies]
executor-macros = { path = "../executor-macros", optional = true }
futures = "0.3.31"

[features]
default = ["std"]
std = ["executor-macros"]
no-std = []
